trigger:
- main
- feature/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Pipeline
    jobs:
    - job: Build
      steps:
      - task: Npm@1
        displayName: NPM Install
        inputs:
          command: install
          workingDir: .
      - task: Npm@1
        displayName: Generate
        inputs:
          command: 'custom'
          customCommand: 'run puff'
    - task: CopyFiles@2
      displayName: Copy Artifacts (json)
      inputs:
        SourceFolder: '.'
        Contents: |
          *.js
          *.json
          !node_modules/**/*
          !.git/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'