trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Pipeline
    jobs:
    - job: Build
      steps:
      - task: Npm@1
        displayName: NPM Install
        inputs:
          command: install
          workingDir: .
      - task: Npm@1
        displayName: Generate
        inputs:
          command: 'custom'
          customCommand: 'run puff'